services:
  - type: web
    name: hemato-vision
    env: python
    pythonVersion: "3.10"            # ← specify the version here
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

    envVars:
      - key: PORT
        value: 10000
